version: '3.4'

services:
  catalog.db:
    container_name: catalog.db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db 
    

  basket.db:
    container_name: basket.db
    restart: always
    ports:
      - 6379:6379

  discount.db:
    container_name: discount.db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin 
      - POSTGRES_PASSWORD=123Admin 
      - POSTGRES_DB=Discount
    volumes:
        - discount_data:/var/lib/postgresql/data 
   

  order.db:
    container_name: order.db
    restart: always
    ports:
        - "1434:1433"
    environment:
      SA_PASSWORD: "SwN12345678"
      ACCEPT_EULA: "Y"

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
    - "5672:5672"
    - "15672:15672"

  pgadmin:
    container_name: pgadmin
    restart: always
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnet.com  
      - PGADMIN_DEFAULT_PASSWORD=123Admin
    volumes:
      - pgadmin_data:/root/.pgadmin 
      
  portainer:
    container_name: portainer
    restart: always
    ports:
      - 8080:8000
      - 9000:9000
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8000:80"
    depends_on:
      - catalog.db

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8001:80"
    depends_on:
      - basket.db
      - discount.api
      - rabbitmq


  discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8002:80"
    depends_on:
     - discount.db


  discount.grpc:
    container_name: discount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "8003:80"
      - "443"
    depends_on:
     - discount.db
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  ordering.api:
    container_name: ordering.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8004:80"
    depends_on:
      - order.db 
      - rabbitmq


  ocelotapigateway:
    container_name: ocelot.apigateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8010:80"

